USE ppdai;
DROP TABLE IF EXISTS loanInfo;
CREATE TABLE loanInfo(
	id INT(12) PRIMARY KEY AUTO_INCREMENT COMMENT '主键', 
	listingId INT(12) NOT NULL COMMENT '列表ID',
	title VARCHAR(128) COMMENT '标的标题',
	creditCode VARCHAR(2) COMMENT '标的级别',
	amount DOUBLE(12, 2) COMMENT '借款金额',
	rate DOUBLE(6, 4) COMMENT '利率',
	months INT(8) COMMENT '期限',
	payWay INT(2) COMMENT '还款方式(0:等额本息(按月还款) 1:一次性还本付息)',
	remainFunding DOUBLE(12, 2) COMMENT '可投标金额',
	preAuditTime VARCHAR(32) COMMENT '预审时间',	
	fistBidTime VARCHAR(32) COMMENT '首次投资时间',
	lastBidTime VARCHAR(32) COMMENT '末笔投资时间',
	lenderCount INT(8) COMMENT '投标人数',
	auditingTime VARCHAR(32) COMMENT '成交日期',
	deadLineTimeOrRemindTimeStr VARCHAR(32) COMMENT '截止时间',
	currentRate DOUBLE(6, 4) COMMENT '利率',
	borrowName VARCHAR(64) COMMENT '借款人的用户名',
	gender INT(1) COMMENT '性别 1 男 2 女 0 未知',
	educationDegree VARCHAR(32) COMMENT '学历',
	graduateSchool VARCHAR(64) COMMENT '毕业院校',
	studyStyle VARCHAR(32) COMMENT '学习形式',
	age INT(3) COMMENT '年龄',
	successCount INT(8) COMMENT '成功借款次数',
	wasteCount INT(8) COMMENT '流标次数',
	cancelCount INT(8) COMMENT '撤标次数',
	failedCount INT(8) COMMENT '失败次数',
	normalCount INT(8) COMMENT '正常还清次数',
	overdueLessCount INT(8) COMMENT '逾期(1-15)还清次数',
	overdueMoreCount INT(8) COMMENT '逾期(15天以上)还清次数',
	owingPrincipal DOUBLE(12, 2) COMMENT '剩余待还本金',
	owingAmount DOUBLE(12, 2) COMMENT '待还金额',
	amountToReceive DOUBLE(12, 2) COMMENT '待收金额',
	firstSuccessBorrowTime VARCHAR(32) COMMENT '第一次成功借款时间',
	registerTime VARCHAR(32) COMMENT '注册时间',
	certificateValidate INT(1) COMMENT '学历认证 0 未认证 1已认证',
	nciicIdentityCheck INT(1) COMMENT '户籍认证 0 未认证 1已认证',
	phoneValidate INT(1) COMMENT '手机认证 0 未认证 1已认证',
	videoValidate INT(1) COMMENT '视屏认证 0 未认证 1已认证',
	creditValidate INT(1) COMMENT '征信认证 0 未认证 1已认证',
	educateValidate INT(1) COMMENT '学籍认证 0 未认证 1已认证',
	lastSuccessBorrowTime VARCHAR(32) COMMENT '最后一次成功借款时间',
	highestPrincipal DOUBLE(12, 2) COMMENT '单笔最高借款金额',
	highestDebt DOUBLE(12, 2) COMMENT '历史最高负债',
	totalPrincipal DOUBLE(12, 2) COMMENT '累计借款金额',
	insertTime varchar(32) COMMENT '数据爬取时间',
	lastupdateTime varchar(32) COMMENT '数据最后更新时间',
	isBid BOOLEAN DEFAULT FALSE comment '是否已投标',
	UNIQUE KEY username_listingid (listingId)
);
DROP TABLE IF EXISTS debtinfo;
CREATE TABLE debtinfo(
	id INT(12) PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
	debtdealId INT(12) NOT NULL COMMENT '债权ID',
	owingNumber INT(4) NOT NULL COMMENT '剩余期数',
	priceforSale DOUBLE(12, 2) COMMENT '转让价',
	listingId INT(12) NOT NULL COMMENT '列表ID',
	creditCode VARCHAR(4) COMMENT '列表等级',
	debtId INT(12) COMMENT '债转编号',
	seller VARCHAR(32) COMMENT '转出人',
	statusId INT(2) COMMENT '1出售中2已完成 0其它无效状态',
	lender VARCHAR(32) COMMENT '投标人',
	bidDateTime VARCHAR(32) COMMENT '投标时间',
	owingPrincipal DOUBLE(12, 2) COMMENT '待还本金',
	owingInterest DOUBLE(12, 2) COMMENT '待收利息',
	days INT(8) COMMENT '距离下次还款的天数',
	priceforSaleRate DOUBLE(12, 2) COMMENT '转让价利率',
	preferenceDegree DOUBLE(12, 2) COMMENT '优惠度',
	listingAmount DOUBLE(12, 2) COMMENT '发标金额',
	listingMonths INT(8) COMMENT '标期限',
	listingTime VARCHAR(32) COMMENT '发标时间',
	listingRate DOUBLE(12, 3) COMMENT '标的利率',
	pastDueNumber INT(8) COMMENT '曾逾期期数',
	currentCreditCode VARCHAR(4) COMMENT '当前评级',
	allowanceRadio DOUBLE(12, 2) COMMENT '折让比例（%号之前的数值）',
	pastDueDay INT(8) COMMENT '曾最大逾期天数',
	insertTime VARCHAR(32) COMMENT '数据爬取时间',
	lastupdateTime VARCHAR(32) COMMENT '数据最后更新时间',
	isBid BOOLEAN COMMENT '是否已投标（0:未投标， 1:已投标）',
	UNIQUE KEY username_listingid (debtdealId)
);
